In [ ]:


import joblib

X_train = joblib.load(
    "X_train_strat.pkl"
)

X_test = joblib.load(
    "X_test_strat.pkl"
)

y_train = joblib.load(
    "y_train_strat.pkl"
)

y_test = joblib.load(
    "y_test_strat.pkl"
)

In [ ]:


import numpy as np
import optuna

from sklearn.pipeline import Pipeline

from sklearn.impute import SimpleImputer

from sklearn.preprocessing import StandardScaler

from sklearn.feature_selection import (
    VarianceThreshold,
    SelectKBest,
    f_regression
)

from sklearn.svm import SVR

from sklearn.model_selection import cross_val_score

from sklearn.metrics import (
    r2_score,
    mean_absolute_error,
    mean_squared_error
)

In [ ]:
preprocessor = Pipeline([

    (
        "imputer",
        SimpleImputer(strategy="median")
    ),

    (
        "variance_filter",
        VarianceThreshold(threshold=0.01)
    ),

    (
        "scaler",
        StandardScaler()
    ),

    (
        "feature_selection",
        SelectKBest(
            score_func=f_regression,
            k=1000
        )
    )

])

In [ ]:
from lightgbm import LGBMRegressor

from xgboost import XGBRegressor

from catboost import CatBoostRegressor

from sklearn.ensemble import RandomForestRegressor

from sklearn.svm import SVR

from sklearn.ensemble import ExtraTreesRegressor

from sklearn.ensemble import HistGradientBoostingRegressor

from sklearn.neural_network import MLPRegressor

In [ ]:

# MODEL PIPELINES


lgbm_pipeline = Pipeline([

    ("preprocessing", preprocessor),

    (
        "model",
        LGBMRegressor(
            n_estimators=300,
            random_state=42
        )
    )

])


xgb_pipeline = Pipeline([

    ("preprocessing", preprocessor),

    (
        "model",
        XGBRegressor(
            n_estimators=300,
            random_state=42
        )
    )

])


cat_pipeline = Pipeline([

    ("preprocessing", preprocessor),

    (
        "model",
        CatBoostRegressor(
            iterations=300,
            verbose=0,
            random_state=42,
            allow_writing_files=False
        )
    )

])


rf_pipeline = Pipeline([

    ("preprocessing", preprocessor),

    (
        "model",
        RandomForestRegressor(
            n_estimators=300,
            random_state=42,
            n_jobs=-1, 
            max_depth=6
        )
    )

])

svr_pipeline = Pipeline([

    ("preprocessing", preprocessor),

    (
        "model",
        SVR(
            kernel="rbf",
            C=10,
            epsilon=0.1
        )
    )

])

mlp_pipeline = Pipeline([
    
    ('preprocessor', preprocessor),
    (
        'model',MLPRegressor (
    
    
                hidden_layer_sizes = (256,128),
                activation = 'relu',
                solver = 'adam',
                alpha = 0.0001,
                batch_size = 'auto',
                learning_rate = 'adaptive',
                learning_rate_init = 0.0001,
                max_iter = 500,
                early_stopping= True,
                random_state = 42
        )
        
    )
    
])

et_pipeline = Pipeline([

    ("preprocessing", preprocessor),

    (
        "model",
        ExtraTreesRegressor(

            n_estimators=300,

            random_state=42,

            n_jobs=-1,

            max_depth=10

        )
    )

])

hist_pipeline = Pipeline([

    ("preprocessing", preprocessor),

    (
        "model",
        HistGradientBoostingRegressor(

            max_iter=300,

            learning_rate=0.05,

            max_depth=6,

            random_state=42

        )
    )

])



# STORE ALL MODELS


models = {

    "LightGBM": lgbm_pipeline,

    "XGBoost": xgb_pipeline,

    "CatBoost": cat_pipeline,

    "RandomForest": rf_pipeline,
    
    "SVR": svr_pipeline,
    
    "MLPRegressor": mlp_pipeline,
    
    "ExtraTreesRegressor": et_pipeline, 
    
    "HistGradientBoostingRegressor": hist_pipeline
    

}


models = {

    "LightGBM": lgbm_pipeline,

    "XGBoost": xgb_pipeline,

    "CatBoost": cat_pipeline,

    "RandomForest": rf_pipeline,

    "ExtraTrees": et_pipeline,

    "HistGradient": hist_pipeline,

    "SVR": svr_pipeline,

    "MLPRegressor": mlp_pipeline

}

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
from sklearn.model_selection import cross_val_score

results = []

for model_name, pipeline in models.items():

    cv_scores = cross_val_score(

        pipeline,

        X_train,

        y_train,

        cv=5,

        scoring="r2",

        n_jobs=-1

    )

    results.append({

        "Model": model_name,

        "CV Mean R2": cv_scores.mean(),

        "CV Std": cv_scores.std()

    })

   
    print(model_name)
   

    print("CV Scores:")
    print(cv_scores)

    print("\nMean CV R2:")
    print(cv_scores.mean())

LightGBM
CV Scores:
[0.80080873 0.7932783  0.76344756 0.81168963 0.77661331]

Mean CV R2:
0.7891675072290723
XGBoost
CV Scores:
[0.77739345 0.75710537 0.7258005  0.79181125 0.74697246]

Mean CV R2:
0.7598166065754601
CatBoost
CV Scores:
[0.80132798 0.7977646  0.76986261 0.80903443 0.76950609]

Mean CV R2:
0.7894991430771664
RandomForest
CV Scores:
[0.75650896 0.73476522 0.70756545 0.75059013 0.70971224]

Mean CV R2:
0.7318283994311038
ExtraTrees
CV Scores:
[0.79234848 0.76979999 0.75664331 0.7839235  0.74517394]

Mean CV R2:
0.7695778426913472
HistGradient
CV Scores:
[0.80898861 0.80055232 0.77445883 0.8156544  0.77731588]

Mean CV R2:
0.7953940081777355
SVR
CV Scores:
[0.77971847 0.78401248 0.76179286 0.78026606 0.75385282]

Mean CV R2:
0.7719285388590801
MLPRegressor
CV Scores:
[0.7748403  0.76364283 0.74481173 0.7659896  0.73020136]

Mean CV R2:
0.7558971638502827

In [ ]:
import pandas as pd

In [ ]:
results_df = pd.DataFrame(results)

results_df = results_df.sort_values(

    by="CV Mean R2",

    ascending=False

)

results_df

          Model  CV Mean R2    CV Std
5  HistGradient    0.795394  0.016655
2      CatBoost    0.789499  0.016584
0      LightGBM    0.789168  0.017198
6           SVR    0.771929  0.011880
4    ExtraTrees    0.769578  0.017246
1       XGBoost    0.759817  0.023074
7  MLPRegressor    0.755897  0.016148
3  RandomForest    0.731828  0.020236

In [ ]:
from sklearn.metrics import (

    r2_score,
    mean_absolute_error,
    mean_squared_error

)

In [ ]:
import numpy as np

In [ ]:
from sklearn.metrics import (

    r2_score,
    mean_absolute_error,
    mean_squared_error

)

test_results = []

for model_name, pipeline in models.items():

    # TRAIN MODEL
  

    pipeline.fit(
        X_train,
        y_train
    )



    
    # TRAIN PREDICTIONS
    

    y_train_pred = pipeline.predict(
        X_train
    )



    
    # TEST PREDICTIONS
    

    y_test_pred = pipeline.predict(
        X_test
    )



    
    # TRAIN METRICS
    

    train_r2 = r2_score(
        y_train,
        y_train_pred
    )

    train_rmse = np.sqrt(
        mean_squared_error(
            y_train,
            y_train_pred
        )
    )



    
    # TEST METRICS
    

    test_r2 = r2_score(
        y_test,
        y_test_pred
    )

    test_rmse = np.sqrt(
        mean_squared_error(
            y_test,
            y_test_pred
        )
    )

    test_mae = mean_absolute_error(
        y_test,
        y_test_pred
    )



    
    # STORE RESULTS
    

    test_results.append({

        "Model": model_name,

        "Train_R2": train_r2,

        "Test_R2": test_r2,

        "Train_RMSE": train_rmse,

        "Test_RMSE": test_rmse,

        "Test_MAE": test_mae
        
        "Train_MAE": train_mae

    })



    
    # PRINT RESULTS
    

    print("\n")
    print(model_name)
    

    print("Train R2 :", train_r2)
    print("Test R2  :", test_r2)

    print("Train RMSE :", train_rmse)
    print("Test RMSE  :", test_rmse)

    print("Test MAE :", test_mae)
    print("Train MAE :", train_mae)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.054766 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 200612
[LightGBM] [Info] Number of data points in the train set: 7984, number of used features: 1000
[LightGBM] [Info] Start training from score -2.889159

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

LightGBM
Train R2 : 0.9538704040663117
Test R2  : 0.8183102774276644
Train RMSE : 0.5106713286871706
Test RMSE  : 0.9924948024651266
Test MAE : 0.6473785118730639


XGBoost
Train R2 : 0.9713005703660904
Test R2  : 0.7963993628064663
Train RMSE : 0.4027989066025257
Test RMSE  : 1.0506368439035736
Test MAE : 0.6840928289335277


CatBoost
Train R2 : 0.9111730015091879
Test R2  : 0.8130911889621321
Train RMSE : 0.7086375211847874
Test RMSE  : 1.0066487246528537
Test MAE : 0.6731939670200369


RandomForest
Train R2 : 0.7783947906748672
Test R2  : 0.7560017954341866
Train RMSE : 1.1192874460592943
Test RMSE  : 1.1501550100355893
Test MAE : 0.8225270922640898


ExtraTrees
Train R2 : 0.8860476253582235
Test R2  : 0.7944613427602055
Train RMSE : 0.8026262144082693
Test RMSE  : 1.0556253665652888
Test MAE : 0.7321214929616316


HistGradient
Train R2 : 0.9146979886439802
Test R2  : 0.8225330185201762
Train RMSE : 0.694434495464393
Test RMSE  : 0.9808934657210662
Test MAE : 0.6509838958160812


SVR
Train R2 : 0.9212351162584559
Test R2  : 0.7905742585401493
Train RMSE : 0.6672951498919878
Test RMSE  : 1.0655604463043808
Test MAE : 0.6869324086901135


MLPRegressor
Train R2 : 0.889991034046615
Test R2  : 0.7460026977298138
Train RMSE : 0.788616194762302
Test RMSE  : 1.1734851879918116
Test MAE : 0.7594608571990938

In [ ]:
results_df = pd.DataFrame(
    test_results
)

results_df = results_df.sort_values(

    by="Test_R2",

    ascending=False

)

results_df

          Model  Train_R2   Test_R2  Train_RMSE  Test_RMSE  Test_MAE
5  HistGradient  0.914698  0.822533    0.694434   0.980893  0.650984
0      LightGBM  0.953870  0.818310    0.510671   0.992495  0.647379
2      CatBoost  0.911173  0.813091    0.708638   1.006649  0.673194
1       XGBoost  0.971301  0.796399    0.402799   1.050637  0.684093
4    ExtraTrees  0.886048  0.794461    0.802626   1.055625  0.732121
6           SVR  0.921235  0.790574    0.667295   1.065560  0.686932
3  RandomForest  0.778395  0.756002    1.119287   1.150155  0.822527
7  MLPRegressor  0.889991  0.746003    0.788616   1.173485  0.759461

In [1]:
import numpy as np

In [2]:
print("Train R2 :", train_r2)

NameError: name 'train_r2' is not defined