In [2]:
import joblib

X_train = joblib.load(
    "X_train_strat.pkl"
)

X_test = joblib.load(
    "X_test_strat.pkl"
)

y_train = joblib.load(
    "y_train_strat.pkl"
)

y_test = joblib.load(
    "y_test_strat.pkl"
)

In [3]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)    
print(y_test.shape)

(7984, 2453)
(1996, 2453)
(7984,)
(1996,)

In [2]:
from sklearn.pipeline import Pipeline

In [3]:
from sklearn.pipeline import Pipeline

from sklearn.impute import SimpleImputer

from sklearn.preprocessing import StandardScaler

from sklearn.feature_selection import (
    VarianceThreshold,
    SelectKBest,
    f_regression
)

In [4]:
preprocessor = Pipeline([

    (
        "imputer",
        SimpleImputer(strategy="median")
    ),

    (
        "variance_filter",
        VarianceThreshold(threshold=0.01)
    ),

    (
        "scaler",
        StandardScaler()
    ),

    (
        "feature_selection",
        SelectKBest(
            score_func=f_regression,
            k=1000
        )
    )

])

In [5]:
from lightgbm import LGBMRegressor

from xgboost import XGBRegressor

from catboost import CatBoostRegressor

from sklearn.ensemble import RandomForestRegressor

from sklearn.svm import SVR

from sklearn.ensemble import ExtraTreesRegressor

from sklearn.ensemble import HistGradientBoostingRegressor

from sklearn.neural_network import MLPRegressor

In [6]:

# MODEL PIPELINES


lgbm_pipeline = Pipeline([

    ("preprocessing", preprocessor),

    (
        "model",
        LGBMRegressor(
            n_estimators=300,
            random_state=42
        )
    )

])


xgb_pipeline = Pipeline([

    ("preprocessing", preprocessor),

    (
        "model",
        XGBRegressor(
            n_estimators=300,
            random_state=42
        )
    )

])


cat_pipeline = Pipeline([

    ("preprocessing", preprocessor),

    (
        "model",
        CatBoostRegressor(
            iterations=300,
            verbose=0,
            random_state=42,
            allow_writing_files=False
        )
    )

])


rf_pipeline = Pipeline([

    ("preprocessing", preprocessor),

    (
        "model",
        RandomForestRegressor(
            n_estimators=300,
            random_state=42,
            n_jobs=-1, 
            max_depth=6
        )
    )

])

svr_pipeline = Pipeline([

    ("preprocessing", preprocessor),

    (
        "model",
        SVR(
            kernel="rbf",
            C=10,
            epsilon=0.1
        )
    )

])

mlp_pipeline = Pipeline([
    
    ('preprocessor', preprocessor),
    (
        'model',MLPRegressor (
    
    
                hidden_layer_sizes = (256,128),
                activation = 'relu',
                solver = 'adam',
                alpha = 0.0001,
                batch_size = 'auto',
                learning_rate = 'adaptive',
                learning_rate_init = 0.0001,
                max_iter = 500,
                early_stopping= True,
                random_state = 42
        )
        
    )
    
])

et_pipeline = Pipeline([

    ("preprocessing", preprocessor),

    (
        "model",
        ExtraTreesRegressor(

            n_estimators=300,

            random_state=42,

            n_jobs=-1,

            max_depth=10

        )
    )

])

hist_pipeline = Pipeline([

    ("preprocessing", preprocessor),

    (
        "model",
        HistGradientBoostingRegressor(

            max_iter=300,

            learning_rate=0.05,

            max_depth=6,

            random_state=42

        )
    )

])



# STORE ALL MODELS


models = {

    "LightGBM": lgbm_pipeline,

    "XGBoost": xgb_pipeline,

    "CatBoost": cat_pipeline,

    "RandomForest": rf_pipeline,
    
    "SVR": svr_pipeline,
    
    "MLPRegressor": mlp_pipeline,
    
    "ExtraTreesRegressor": et_pipeline, 
    
    "HistGradientBoostingRegressor": hist_pipeline
    

}


models = {

    "LightGBM": lgbm_pipeline,

    "XGBoost": xgb_pipeline,

    "CatBoost": cat_pipeline,

    "RandomForest": rf_pipeline,

    "ExtraTrees": et_pipeline,

    "HistGradient": hist_pipeline,

    "SVR": svr_pipeline,

    "MLPRegressor": mlp_pipeline

}

In [7]:
from sklearn.model_selection import cross_val_score

In [8]:
from sklearn.model_selection import cross_val_score

results = []

for model_name, pipeline in models.items():

    cv_scores = cross_val_score(

        pipeline,

        X_train,

        y_train,

        cv=5,

        scoring="r2",

        n_jobs=-1

    )

    results.append({

        "Model": model_name,

        "CV Mean R2": cv_scores.mean(),

        "CV Std": cv_scores.std()

    })

   
    print(model_name)
   

    print("CV Scores:")
    print(cv_scores)

    print("\nMean CV R2:")
    print(cv_scores.mean())

LightGBM
CV Scores:
[0.80840008 0.77373125 0.81293499 0.78623573 0.76850847]

Mean CV R2:
0.7899621050111645
XGBoost
CV Scores:
[0.76899626 0.75352454 0.80147554 0.76287665 0.73826176]

Mean CV R2:
0.7650269498107718
CatBoost
CV Scores:
[0.80473046 0.77723464 0.80043431 0.78807429 0.77958276]

Mean CV R2:
0.7900112923694381
RandomForest
CV Scores:
[0.74000167 0.73012499 0.74277924 0.74653654 0.71566171]

Mean CV R2:
0.7350208319732412
ExtraTrees
CV Scores:
[0.77984962 0.75729346 0.77724094 0.77608916 0.75741187]

Mean CV R2:
0.7695770088802846
HistGradient
CV Scores:
[0.81386599 0.7815609  0.81113323 0.79755877 0.77889962]

Mean CV R2:
0.79660370038995
SVR
CV Scores:
[0.79161939 0.76302133 0.78493059 0.76816203 0.75239365]

Mean CV R2:
0.7720253974011358
MLPRegressor
CV Scores:
[0.78799103 0.75223904 0.77428359 0.74833742 0.7014862 ]

Mean CV R2:
0.7528674541355849

In [9]:
import pandas as pd

In [10]:
results_df = pd.DataFrame(results)

results_df = results_df.sort_values(

    by="CV Mean R2",

    ascending=False

)

results_df

          Model  CV Mean R2    CV Std
5  HistGradient    0.796604  0.014489
2      CatBoost    0.790011  0.010964
0      LightGBM    0.789962  0.017918
6           SVR    0.772025  0.014366
4    ExtraTrees    0.769577  0.010055
1       XGBoost    0.765027  0.020965
7  MLPRegressor    0.752867  0.029507
3  RandomForest    0.735021  0.011103

In [11]:
from sklearn.metrics import (

    r2_score,
    mean_absolute_error,
    mean_squared_error

)

In [12]:
import numpy as np

In [13]:
from sklearn.metrics import (

    r2_score,
    mean_absolute_error,
    mean_squared_error

)

test_results = []

for model_name, pipeline in models.items():

    # TRAIN MODEL
  

    pipeline.fit(
        X_train,
        y_train
    )



    
    # TRAIN PREDICTIONS
    

    y_train_pred = pipeline.predict(
        X_train
    )



    
    # TEST PREDICTIONS
    

    y_test_pred = pipeline.predict(
        X_test
    )



    
    # TRAIN METRICS
    

    train_r2 = r2_score(
        y_train,
        y_train_pred
    )

    train_rmse = np.sqrt(
        mean_squared_error(
            y_train,
            y_train_pred
        )
    )



    
    # TEST METRICS
    

    test_r2 = r2_score(
        y_test,
        y_test_pred
    )

    test_rmse = np.sqrt(
        mean_squared_error(
            y_test,
            y_test_pred
        )
    )

    test_mae = mean_absolute_error(
        y_test,
        y_test_pred
    )



    
    # STORE RESULTS
    

    test_results.append({

        "Model": model_name,

        "Train_R2": train_r2,

        "Test_R2": test_r2,

        "Train_RMSE": train_rmse,

        "Test_RMSE": test_rmse,

        "Test_MAE": test_mae

    })



    
    # PRINT RESULTS
    

    print("\n")
    print(model_name)
    

    print("Train R2 :", train_r2)
    print("Test R2  :", test_r2)

    print("Train RMSE :", train_rmse)
    print("Test RMSE  :", test_rmse)

    print("Test MAE :", test_mae)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.096054 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 194360
[LightGBM] [Info] Number of data points in the train set: 7984, number of used features: 1000
[LightGBM] [Info] Start training from score -2.891766

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

LightGBM
Train R2 : 0.9544336460499425
Test R2  : 0.8124481323241222
Train RMSE : 0.5049851016503696
Test RMSE  : 1.0293140388473967
Test MAE : 0.6680629815258465


XGBoost
Train R2 : 0.9711778116502711
Test R2  : 0.7906063125950974
Train RMSE : 0.4016242261830827
Test RMSE  : 1.087599481710774
Test MAE : 0.72410248153165


CatBoost
Train R2 : 0.9149188025013152
Test R2  : 0.8064211993237432
Train RMSE : 0.6900383416526644
Test RMSE  : 1.0457216438890866
Test MAE : 0.6969936443034687


RandomForest
Train R2 : 0.7810780775637649
Test R2  : 0.7405890826373882
Train RMSE : 1.1068813051834936
Test RMSE  : 1.2105460760023874
Test MAE : 0.8686166217170534


ExtraTrees
Train R2 : 0.8868837366975781
Test R2  : 0.7811337133161448
Train RMSE : 0.7956442909786178
Test RMSE  : 1.1119279175998467
Test MAE : 0.7690348967441313


HistGradient
Train R2 : 0.9141158573591837
Test R2  : 0.8124959982690894
Train RMSE : 0.693286778761559
Test RMSE  : 1.029182682562613
Test MAE : 0.6853759249583317


SVR
Train R2 : 0.925526623367663
Test R2  : 0.7865808611191832
Train RMSE : 0.6455902286209843
Test RMSE  : 1.0980038961166958
Test MAE : 0.7019751552179389


MLPRegressor
Train R2 : 0.9038279167103468
Test R2  : 0.7905940080372293
Train RMSE : 0.7336365126547609
Test RMSE  : 1.0876314364328439
Test MAE : 0.7479381795412529

In [14]:
results_df = pd.DataFrame(
    test_results
)

results_df = results_df.sort_values(

    by="Test_R2",

    ascending=False

)

results_df

          Model  Train_R2   Test_R2  Train_RMSE  Test_RMSE  Test_MAE
5  HistGradient  0.914116  0.812496    0.693287   1.029183  0.685376
0      LightGBM  0.954434  0.812448    0.504985   1.029314  0.668063
2      CatBoost  0.914919  0.806421    0.690038   1.045722  0.696994
1       XGBoost  0.971178  0.790606    0.401624   1.087599  0.724102
7  MLPRegressor  0.903828  0.790594    0.733637   1.087631  0.747938
6           SVR  0.925527  0.786581    0.645590   1.098004  0.701975
4    ExtraTrees  0.886884  0.781134    0.795644   1.111928  0.769035
3  RandomForest  0.781078  0.740589    1.106881   1.210546  0.868617