In [1]:
import joblib

In [ ]:


best_lgbm_pipeline = joblib.load("best_lgbm_pipeline.pkl")
   

X_test = joblib.load("X_test_random.pkl")

y_test = joblib.load("y_test_random.pkl")

In [5]:
X_test.shape

(1996, 2453)

In [16]:
X_test.head()

,DESC_ABC,DESC_ABCGG,DESC_nAcid,DESC_nBase,DESC_SpAbs_A,DESC_SpMax_A,DESC_SpDiam_A,DESC_SpAD_A,DESC_SpMAD_A,DESC_LogEE_A,...,FPMorgan_1014,FPMorgan_1015,FPMorgan_1016,FPMorgan_1017,FPMorgan_1018,FPMorgan_1019,FPMorgan_1020,FPMorgan_1021,FPMorgan_1022,FPMorgan_1023
1253,14.118275,11.564938,0,0,24.108538,2.510136,5.020273,24.108538,1.339363,3.842983,...,0,0,0,0,0,0,0,0,0,0
8224,15.072670,13.730964,0,0,25.101919,2.526561,4.968272,25.101919,1.255096,3.912464,...,0,0,0,0,0,0,0,0,0,0
1658,23.869542,18.219493,0,0,39.555970,2.346647,4.693294,39.555970,1.236124,4.349603,...,0,0,0,1,0,0,0,0,0,0
7733,16.814753,14.335183,0,0,27.783105,2.395003,4.790006,27.783105,1.207961,4.011619,...,0,0,0,0,0,0,0,0,0,0
1441,23.650763,17.455695,0,0,39.463050,2.419220,4.720172,39.463050,1.273002,4.340939,...,0,0,0,1,0,0,0,0,0,0

In [7]:
prediction_1 = best_lgbm_pipeline.predict(X_test)


print(prediction_1[:20])

[-5.35701348 -1.8921495  -6.27435914 -3.76969042 -6.24346282 -1.93588516
 -3.32922162 -4.46770001 -1.66817619 -1.23028369 -4.80275065 -2.11911251
 -4.91790029 -1.46417473 -3.43982941 -3.34473685 -4.44188509 -3.08553616
 -1.27761867 -4.44261813]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [8]:
predictions = best_lgbm_pipeline.predict(X_test)

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [15]:
import pandas as pd 

results =  pd.DataFrame({
    "Actual": y_test,
    "Predicted": predictions,
    "Error": abs(y_test - predictions)
})

results.head(20)

        Actual  Predicted     Error
1253 -5.984242  -5.357013  0.627229
8224 -1.930000  -1.892149  0.037851
1658 -7.300465  -6.274359  1.026106
7733 -3.590000  -3.769690  0.179690
1441 -4.340909  -6.243463  1.902554
1056 -2.153178  -1.935885  0.217293
35   -4.793228  -3.329222  1.464006
7150 -4.552600  -4.467700  0.084900
1662 -7.155088  -1.668176  5.486912
4047 -0.995500  -1.230284  0.234784
39   -4.581333  -4.802751  0.221418
8089 -2.500000  -2.119113  0.380887
8652 -5.298000  -4.917900  0.380100
8493 -0.750000  -1.464175  0.714175
1261 -5.941561  -3.439829  2.501732
7642 -2.560000  -3.344737  0.784737
2945 -3.499701  -4.441885  0.942184
8003 -3.360000  -3.085536  0.274464
2133 -1.335254  -1.277619  0.057635
4304 -4.308700  -4.442618  0.133918

In [18]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

import numpy as np 

r2 = r2_score(y_test, predictions)
mae = mean_absolute_error(y_test, predictions)
mse = mean_squared_error(y_test, predictions) 
rmse = np.sqrt(mse)

print(f"R2 Score: {r2:.4f}")
print(f"Mean Absolute Error: {mae:.4f}")

print(f"Root Mean Squared Error: {rmse:.4f}")

R2 Score: 0.8264
Mean Absolute Error: 0.6379
Root Mean Squared Error: 0.9702

In [2]:
import joblib

In [6]:
features_columns = joblib.load("final_feature_columns.pkl")

print(len(features_columns))

2453