In [1]:
import joblib

X_train = joblib.load(
    "X_train_random.pkl"
)

X_test = joblib.load(
    "X_test_random.pkl"
)

y_train = joblib.load(
    "y_train_random.pkl"
)

y_test = joblib.load(
    "y_test_random.pkl"
)

In [2]:
from sklearn.pipeline import Pipeline

from sklearn.impute import SimpleImputer

from sklearn.preprocessing import StandardScaler

from sklearn.feature_selection import (
    VarianceThreshold,
    SelectKBest,
    f_regression
)

In [3]:
preprocessor = Pipeline([

    (
        "imputer",
        SimpleImputer(strategy="median")
    ),

    (
        "variance_filter",
        VarianceThreshold(threshold=0.01)
    ),

    (
        "scaler",
        StandardScaler()
    ),

    (
        "feature_selection",
        SelectKBest(
            score_func=f_regression,
            k=1000
        )
    )

])

In [8]:
import optuna

from lightgbm import LGBMRegressor

from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_validate

In [ ]:

import numpy as np

def objective(trial):

    model = LGBMRegressor(

        n_estimators=trial.suggest_int(
            "n_estimators",
            200,
            1500
        ),

        learning_rate=trial.suggest_float(
            "learning_rate",
            0.01,
            0.3,
            log=True
        ),

        max_depth=trial.suggest_int(
            "max_depth",
            3,
            15
        ),

        num_leaves=trial.suggest_int(
            "num_leaves",
            20,
            300
        ),

        min_child_samples=trial.suggest_int(
            "min_child_samples",
            5,
            100
        ),

        subsample=trial.suggest_float(
            "subsample",
            0.6,
            1.0
        ),

        colsample_bytree=trial.suggest_float(
            "colsample_bytree",
            0.6,
            1.0
        ),

        reg_alpha=trial.suggest_float(
            "reg_alpha",
            0,
            10
        ),

        reg_lambda=trial.suggest_float(
            "reg_lambda",
            0,
            10
        ),

        random_state=42,
        n_jobs=-1,
        verbose=-1
    )

    pipeline = Pipeline([

        (
            "preprocessing",
            preprocessor
        ),

        (
            "model",
            model
        )

    ])

    scores = cross_validate(

        pipeline,

        X_train,

        y_train,

        cv=5,

        scoring={

            "r2": "r2",

            "mae": "neg_mean_absolute_error"

        },

        n_jobs=-1

    )

    mean_r2 = np.mean(
        scores["test_r2"]
    )

    mean_mae = -np.mean(
        scores["test_mae"]
    )

    trial.set_user_attr(
        "mean_r2",
        mean_r2
    )

    trial.set_user_attr(
        "mean_mae",
        mean_mae
    )

    print(
        f"Trial {trial.number} | "
        f"Mean R2 = {mean_r2:.4f} | "
        f"Mean MAE = {mean_mae:.4f}"
    )

    return mean_r2

In [10]:
study = optuna.create_study(
    direction="maximize"
)

study.optimize(
    objective,
    n_trials=30,
    show_progress_bar=True
)

[I 2026-06-08 19:24:39,405] A new study created in memory with name: no-name-12c96fcb-0a3e-42b8-93fe-3efc6f6e0759

  0%|          | 0/30 [00:00<?, ?it/s]

Trial 0 | Mean R2 = 0.7972 | Mean MAE = 0.7064
[I 2026-06-08 19:30:17,711] Trial 0 finished with value: 0.7971722363927045 and parameters: {'n_estimators': 861, 'learning_rate': 0.012387255900948713, 'max_depth': 13, 'num_leaves': 98, 'min_child_samples': 53, 'subsample': 0.6773226548380518, 'colsample_bytree': 0.7712581527264397, 'reg_alpha': 7.366717054023417, 'reg_lambda': 0.01629711493132957}. Best is trial 0 with value: 0.7971722363927045.
Trial 1 | Mean R2 = 0.7928 | Mean MAE = 0.7067
[I 2026-06-08 19:33:43,530] Trial 1 finished with value: 0.7927948511685508 and parameters: {'n_estimators': 852, 'learning_rate': 0.08685614153294546, 'max_depth': 14, 'num_leaves': 107, 'min_child_samples': 86, 'subsample': 0.7753617203216898, 'colsample_bytree': 0.7590607294286353, 'reg_alpha': 5.660905332121269, 'reg_lambda': 1.3923068945213124}. Best is trial 0 with value: 0.7971722363927045.
Trial 2 | Mean R2 = 0.7785 | Mean MAE = 0.7451
[I 2026-06-08 19:34:41,858] Trial 2 finished with value: 0.7784969433249863 and parameters: {'n_estimators': 1070, 'learning_rate': 0.2792998202916571, 'max_depth': 15, 'num_leaves': 54, 'min_child_samples': 30, 'subsample': 0.8793717575194673, 'colsample_bytree': 0.7992188131767751, 'reg_alpha': 6.979376273988405, 'reg_lambda': 4.64039498516568}. Best is trial 0 with value: 0.7971722363927045.
Trial 3 | Mean R2 = 0.7987 | Mean MAE = 0.7082
[I 2026-06-08 19:37:31,583] Trial 3 finished with value: 0.7986730754080382 and parameters: {'n_estimators': 939, 'learning_rate': 0.01443657944448182, 'max_depth': 10, 'num_leaves': 77, 'min_child_samples': 94, 'subsample': 0.6266492062706431, 'colsample_bytree': 0.7261960303155435, 'reg_alpha': 8.977660717816137, 'reg_lambda': 4.456845432563236}. Best is trial 3 with value: 0.7986730754080382.
Trial 4 | Mean R2 = 0.7967 | Mean MAE = 0.7135
[I 2026-06-08 19:39:14,079] Trial 4 finished with value: 0.7967055082688835 and parameters: {'n_estimators': 1040, 'learning_rate': 0.02942776208248794, 'max_depth': 5, 'num_leaves': 109, 'min_child_samples': 54, 'subsample': 0.8813639711927039, 'colsample_bytree': 0.8190950371362069, 'reg_alpha': 2.12782059196695, 'reg_lambda': 7.439480996099893}. Best is trial 3 with value: 0.7986730754080382.
Trial 5 | Mean R2 = 0.7927 | Mean MAE = 0.7030
[I 2026-06-08 19:42:39,220] Trial 5 finished with value: 0.7927261992791987 and parameters: {'n_estimators': 1314, 'learning_rate': 0.048970308038064056, 'max_depth': 15, 'num_leaves': 264, 'min_child_samples': 68, 'subsample': 0.7422791856421772, 'colsample_bytree': 0.6738169004978257, 'reg_alpha': 2.8821788826320494, 'reg_lambda': 6.594755442377851}. Best is trial 3 with value: 0.7986730754080382.
Trial 6 | Mean R2 = 0.7914 | Mean MAE = 0.7138
[I 2026-06-08 19:44:02,565] Trial 6 finished with value: 0.7914022082894976 and parameters: {'n_estimators': 1041, 'learning_rate': 0.1004384780782007, 'max_depth': 5, 'num_leaves': 137, 'min_child_samples': 85, 'subsample': 0.9400148946694745, 'colsample_bytree': 0.8656330315028167, 'reg_alpha': 4.202493552647606, 'reg_lambda': 0.32938488730243964}. Best is trial 3 with value: 0.7986730754080382.
Trial 7 | Mean R2 = 0.7843 | Mean MAE = 0.7496
[I 2026-06-08 19:44:47,190] Trial 7 finished with value: 0.7842839982916952 and parameters: {'n_estimators': 679, 'learning_rate': 0.02068876852043923, 'max_depth': 4, 'num_leaves': 204, 'min_child_samples': 81, 'subsample': 0.6892407752726164, 'colsample_bytree': 0.8503988853572888, 'reg_alpha': 4.499549138642731, 'reg_lambda': 6.149328769303773}. Best is trial 3 with value: 0.7986730754080382.
Trial 8 | Mean R2 = 0.7973 | Mean MAE = 0.7031
[I 2026-06-08 19:47:36,403] Trial 8 finished with value: 0.7973164322028768 and parameters: {'n_estimators': 831, 'learning_rate': 0.04838388585286284, 'max_depth': 14, 'num_leaves': 105, 'min_child_samples': 77, 'subsample': 0.8625278353730205, 'colsample_bytree': 0.7346265716607219, 'reg_alpha': 9.992989560430273, 'reg_lambda': 7.127218529144717}. Best is trial 3 with value: 0.7986730754080382.
Trial 9 | Mean R2 = 0.7848 | Mean MAE = 0.7509
[I 2026-06-08 19:48:46,976] Trial 9 finished with value: 0.7848304375870505 and parameters: {'n_estimators': 761, 'learning_rate': 0.01090765088304722, 'max_depth': 5, 'num_leaves': 43, 'min_child_samples': 54, 'subsample': 0.7072647380233065, 'colsample_bytree': 0.8113953020865142, 'reg_alpha': 4.752621859419933, 'reg_lambda': 8.311593908587447}. Best is trial 3 with value: 0.7986730754080382.
Trial 10 | Mean R2 = 0.7895 | Mean MAE = 0.7339
[I 2026-06-08 19:49:53,284] Trial 10 finished with value: 0.7895380819366619 and parameters: {'n_estimators': 345, 'learning_rate': 0.021987731932691688, 'max_depth': 10, 'num_leaves': 201, 'min_child_samples': 100, 'subsample': 0.6072859829746694, 'colsample_bytree': 0.9986950125045431, 'reg_alpha': 0.25611992286737806, 'reg_lambda': 3.3497798380606985}. Best is trial 3 with value: 0.7986730754080382.
Trial 11 | Mean R2 = 0.7987 | Mean MAE = 0.7086
[I 2026-06-08 19:51:10,582] Trial 11 finished with value: 0.7986546967395649 and parameters: {'n_estimators': 455, 'learning_rate': 0.04898216479187804, 'max_depth': 10, 'num_leaves': 24, 'min_child_samples': 7, 'subsample': 0.8379671788731904, 'colsample_bytree': 0.6123401179972423, 'reg_alpha': 9.572440704567079, 'reg_lambda': 9.4834394605029}. Best is trial 3 with value: 0.7986730754080382.
Trial 12 | Mean R2 = 0.7898 | Mean MAE = 0.7167
[I 2026-06-08 19:52:30,124] Trial 12 finished with value: 0.7897550827698931 and parameters: {'n_estimators': 401, 'learning_rate': 0.15959320328803836, 'max_depth': 9, 'num_leaves': 29, 'min_child_samples': 6, 'subsample': 0.81884889094601, 'colsample_bytree': 0.608234993954651, 'reg_alpha': 9.563797609369495, 'reg_lambda': 9.473591337290957}. Best is trial 3 with value: 0.7986730754080382.
Trial 13 | Mean R2 = 0.7977 | Mean MAE = 0.6967
[I 2026-06-08 19:54:30,315] Trial 13 finished with value: 0.7977328275831763 and parameters: {'n_estimators': 560, 'learning_rate': 0.03615646638559975, 'max_depth': 10, 'num_leaves': 64, 'min_child_samples': 20, 'subsample': 0.6084695457533316, 'colsample_bytree': 0.604505385167665, 'reg_alpha': 8.19772502265621, 'reg_lambda': 3.9566353519107698}. Best is trial 3 with value: 0.7986730754080382.
Trial 14 | Mean R2 = 0.7997 | Mean MAE = 0.7041
[I 2026-06-08 19:57:01,035] Trial 14 finished with value: 0.7996943980974882 and parameters: {'n_estimators': 1493, 'learning_rate': 0.016787431772564917, 'max_depth': 8, 'num_leaves': 21, 'min_child_samples': 35, 'subsample': 0.98660764611885, 'colsample_bytree': 0.683989617620858, 'reg_alpha': 8.53420867240165, 'reg_lambda': 2.4813520991846456}. Best is trial 14 with value: 0.7996943980974882.
Trial 15 | Mean R2 = 0.7987 | Mean MAE = 0.6963
[I 2026-06-08 20:02:11,793] Trial 15 finished with value: 0.7987464985555854 and parameters: {'n_estimators': 1470, 'learning_rate': 0.016403359206367894, 'max_depth': 8, 'num_leaves': 75, 'min_child_samples': 34, 'subsample': 0.9685045770719332, 'colsample_bytree': 0.7010503370135057, 'reg_alpha': 8.072818919293034, 'reg_lambda': 2.6149698978597957}. Best is trial 14 with value: 0.7996943980974882.
Trial 16 | Mean R2 = 0.7996 | Mean MAE = 0.6939
[I 2026-06-08 20:07:47,149] Trial 16 finished with value: 0.7995841515623813 and parameters: {'n_estimators': 1481, 'learning_rate': 0.01982527910521885, 'max_depth': 7, 'num_leaves': 153, 'min_child_samples': 35, 'subsample': 0.9816898718662598, 'colsample_bytree': 0.6784538510469883, 'reg_alpha': 6.405012910920246, 'reg_lambda': 2.542547236515962}. Best is trial 14 with value: 0.7996943980974882.
Trial 17 | Mean R2 = 0.7974 | Mean MAE = 0.6962
[I 2026-06-08 20:13:15,482] Trial 17 finished with value: 0.7973772267688212 and parameters: {'n_estimators': 1499, 'learning_rate': 0.02730562682084077, 'max_depth': 7, 'num_leaves': 299, 'min_child_samples': 39, 'subsample': 0.9931544740708285, 'colsample_bytree': 0.6643786944950165, 'reg_alpha': 6.181058111153423, 'reg_lambda': 2.1596656139684978}. Best is trial 14 with value: 0.7996943980974882.
Trial 18 | Mean R2 = 0.7957 | Mean MAE = 0.7028
[I 2026-06-08 20:21:55,033] Trial 18 finished with value: 0.7957280853220355 and parameters: {'n_estimators': 1266, 'learning_rate': 0.019043995032808198, 'max_depth': 7, 'num_leaves': 164, 'min_child_samples': 21, 'subsample': 0.9237011368922439, 'colsample_bytree': 0.9251802298655659, 'reg_alpha': 6.253470556525064, 'reg_lambda': 5.493473014376381}. Best is trial 14 with value: 0.7996943980974882.
Trial 19 | Mean R2 = 0.7995 | Mean MAE = 0.6992
[I 2026-06-08 20:56:57,343] Trial 19 finished with value: 0.7994771526999579 and parameters: {'n_estimators': 1289, 'learning_rate': 0.01004522238532122, 'max_depth': 12, 'num_leaves': 209, 'min_child_samples': 46, 'subsample': 0.9178603748918618, 'colsample_bytree': 0.6671573446128474, 'reg_alpha': 8.323272653122432, 'reg_lambda': 1.601385880108261}. Best is trial 14 with value: 0.7996943980974882.
Trial 20 | Mean R2 = 0.7802 | Mean MAE = 0.7624
[I 2026-06-08 20:57:25,942] Trial 20 finished with value: 0.7802192004762113 and parameters: {'n_estimators': 214, 'learning_rate': 0.08760619414902059, 'max_depth': 3, 'num_leaves': 160, 'min_child_samples': 22, 'subsample': 0.9897000451698262, 'colsample_bytree': 0.6476519257154516, 'reg_alpha': 7.194568626664697, 'reg_lambda': 3.1703528306085498}. Best is trial 14 with value: 0.7996943980974882.
Trial 21 | Mean R2 = 0.7990 | Mean MAE = 0.6996
[I 2026-06-08 21:13:43,074] Trial 21 finished with value: 0.7989539442299356 and parameters: {'n_estimators': 1275, 'learning_rate': 0.010250609249455254, 'max_depth': 12, 'num_leaves': 225, 'min_child_samples': 44, 'subsample': 0.9287068151519305, 'colsample_bytree': 0.7009173273129449, 'reg_alpha': 8.382249983323998, 'reg_lambda': 1.4124191827256412}. Best is trial 14 with value: 0.7996943980974882.
Trial 22 | Mean R2 = 0.8000 | Mean MAE = 0.7005
[I 2026-06-08 21:21:09,061] Trial 22 finished with value: 0.8000159560937667 and parameters: {'n_estimators': 1379, 'learning_rate': 0.013572190202010032, 'max_depth': 8, 'num_leaves': 240, 'min_child_samples': 65, 'subsample': 0.9511809181066476, 'colsample_bytree': 0.643950505060322, 'reg_alpha': 7.518494200066749, 'reg_lambda': 1.322878179937905}. Best is trial 22 with value: 0.8000159560937667.
Trial 23 | Mean R2 = 0.8000 | Mean MAE = 0.7000
[I 2026-06-08 21:25:26,437] Trial 23 finished with value: 0.8000341298884119 and parameters: {'n_estimators': 1402, 'learning_rate': 0.015213162868776496, 'max_depth': 7, 'num_leaves': 238, 'min_child_samples': 61, 'subsample': 0.9578486268536361, 'colsample_bytree': 0.6422902514180014, 'reg_alpha': 5.540119448046517, 'reg_lambda': 1.0514787338804057}. Best is trial 23 with value: 0.8000341298884119.
Trial 24 | Mean R2 = 0.7995 | Mean MAE = 0.7017
[I 2026-06-08 21:28:22,881] Trial 24 finished with value: 0.7994852510246675 and parameters: {'n_estimators': 1384, 'learning_rate': 0.014108604497089438, 'max_depth': 8, 'num_leaves': 247, 'min_child_samples': 65, 'subsample': 0.9623515349397228, 'colsample_bytree': 0.6469377703727776, 'reg_alpha': 3.571384170523448, 'reg_lambda': 0.7430706968695767}. Best is trial 23 with value: 0.8000341298884119.
Trial 25 | Mean R2 = 0.7999 | Mean MAE = 0.7003
[I 2026-06-08 21:31:34,425] Trial 25 finished with value: 0.7999039578689647 and parameters: {'n_estimators': 1146, 'learning_rate': 0.02834351262963488, 'max_depth': 6, 'num_leaves': 286, 'min_child_samples': 66, 'subsample': 0.8898670115809117, 'colsample_bytree': 0.6401329879744868, 'reg_alpha': 5.484287142948491, 'reg_lambda': 1.062436423203263}. Best is trial 23 with value: 0.8000341298884119.
Trial 26 | Mean R2 = 0.7997 | Mean MAE = 0.7004
[I 2026-06-08 21:35:12,624] Trial 26 finished with value: 0.7997359354716679 and parameters: {'n_estimators': 1175, 'learning_rate': 0.02710656572453794, 'max_depth': 6, 'num_leaves': 298, 'min_child_samples': 66, 'subsample': 0.9036863070469917, 'colsample_bytree': 0.6373984988182456, 'reg_alpha': 5.320245461708557, 'reg_lambda': 0.7573402074706179}. Best is trial 23 with value: 0.8000341298884119.
Trial 27 | Mean R2 = 0.7983 | Mean MAE = 0.7018
[I 2026-06-08 21:37:39,474] Trial 27 finished with value: 0.7983491977435869 and parameters: {'n_estimators': 1136, 'learning_rate': 0.03824709236139165, 'max_depth': 6, 'num_leaves': 263, 'min_child_samples': 70, 'subsample': 0.9486437483676776, 'colsample_bytree': 0.7249801615332215, 'reg_alpha': 5.409753093211993, 'reg_lambda': 1.6573778723938113}. Best is trial 23 with value: 0.8000341298884119.
Trial 28 | Mean R2 = 0.7980 | Mean MAE = 0.7008
[I 2026-06-08 21:39:56,713] Trial 28 finished with value: 0.7980306438451994 and parameters: {'n_estimators': 1372, 'learning_rate': 0.03411797854536795, 'max_depth': 6, 'num_leaves': 266, 'min_child_samples': 61, 'subsample': 0.8457258148114919, 'colsample_bytree': 0.6334936207558672, 'reg_alpha': 3.512606072502021, 'reg_lambda': 3.5395879597262017}. Best is trial 23 with value: 0.8000341298884119.
Trial 29 | Mean R2 = 0.7938 | Mean MAE = 0.7218
[I 2026-06-08 21:41:07,776] Trial 29 finished with value: 0.7938374524695906 and parameters: {'n_estimators': 1220, 'learning_rate': 0.06497160532837548, 'max_depth': 3, 'num_leaves': 237, 'min_child_samples': 58, 'subsample': 0.8942801395256137, 'colsample_bytree': 0.7574884345561321, 'reg_alpha': 7.470996862690411, 'reg_lambda': 0.011509867910762361}. Best is trial 23 with value: 0.8000341298884119.

In [11]:
print("Best Mean CV R2:")
print(study.best_value)

print("\nBest Parameters:")
print(study.best_params)

Best Mean CV R2:
0.8000341298884119

Best Parameters:
{'n_estimators': 1402, 'learning_rate': 0.015213162868776496, 'max_depth': 7, 'num_leaves': 238, 'min_child_samples': 61, 'subsample': 0.9578486268536361, 'colsample_bytree': 0.6422902514180014, 'reg_alpha': 5.540119448046517, 'reg_lambda': 1.0514787338804057}

In [12]:
best_lgbm_pipeline = Pipeline([

    (
        "preprocessing",
        preprocessor
    ),

    (
        "model",

        LGBMRegressor(

            **study.best_params,

            random_state=42,

            n_jobs=-1,

            verbose=-1
        )
    )

])

In [13]:
best_lgbm_pipeline.fit(
    X_train,
    y_train
)

Pipeline(steps=[('preprocessing',
                 Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                                 ('variance_filter',
                                  VarianceThreshold(threshold=0.01)),
                                 ('scaler', StandardScaler()),
                                 ('feature_selection',
                                  SelectKBest(k=1000,
                                              score_func=<function f_regression at 0x00000222C3165AB0>))])),
                ('model',
                 LGBMRegressor(colsample_bytree=0.6422902514180014,
                               learning_rate=0.015213162868776496, max_depth=7,
                               min_child_samples=61, n_estimators=1402,
                               n_jobs=-1, num_leaves=238, random_state=42,
                               reg_alpha=5.540119448046517,
                               reg_lambda=1.0514787338804057,
                               subsample=0.9578486268536361, verbose=-1))])

In [14]:
y_train_pred = best_lgbm_pipeline.predict(
    X_train
)

y_test_pred = best_lgbm_pipeline.predict(
    X_test
)

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [18]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [19]:
train_r2 = r2_score(
    y_train,
    y_train_pred
)

test_r2 = r2_score(
    y_test,
    y_test_pred
)

train_rmse = np.sqrt(
    mean_squared_error(
        y_train,
        y_train_pred
    )
)

test_rmse = np.sqrt(
    mean_squared_error(
        y_test,
        y_test_pred
    )
)

train_mae = mean_absolute_error(
    y_train,
    y_train_pred
)

test_mae = mean_absolute_error(
    y_test,
    y_test_pred
)

In [20]:
print("\n TUNED LIGHTGBM ")

print("\nTrain R2 :", train_r2)
print("Train RMSE :", train_rmse)
print("Train MAE :", train_mae)

print("\nTest R2 :", test_r2)
print("Test RMSE :", test_rmse)
print("Test MAE :", test_mae)

 TUNED LIGHTGBM

Train R2 : 0.9275909737700555
Train RMSE : 0.6398055508604502
Train MAE : 0.386765577781781

Test R2 : 0.8263960766749234
Test RMSE : 0.9701588015433897
Test MAE : 0.6379423633367385

In [21]:
import pandas as pd

trials_df = study.trials_dataframe()

trials_df["Mean_CV_MAE"] = [
    t.user_attrs.get("mean_mae")
    for t in study.trials
]

trials_df["Mean_CV_R2"] = [
    t.user_attrs.get("mean_r2")
    for t in study.trials
]

final_trials_df = trials_df[
    [
        "number",
        "Mean_CV_R2",
        "Mean_CV_MAE",
        "params_n_estimators",
        "params_learning_rate",
        "params_max_depth",
        "params_num_leaves",
        "params_min_child_samples",
        "params_subsample",
        "params_colsample_bytree",
        "params_reg_alpha",
        "params_reg_lambda",
        "state"
    ]
].copy()

final_trials_df.columns = [
    "Trial_Number",
    "Mean_CV_R2",
    "Mean_CV_MAE",
    "N_Estimators",
    "Learning_Rate",
    "Max_Depth",
    "Num_Leaves",
    "Min_Child_Samples",
    "Subsample",
    "Colsample_Bytree",
    "Reg_Alpha",
    "Reg_Lambda",
    "Status"
]

final_trials_df.to_csv(
    "lgbm_optuna_trials.csv",
    index=False
)

final_trials_df.head()

,Trial_Number,Mean_CV_R2,Mean_CV_MAE,N_Estimators,Learning_Rate,Max_Depth,Num_Leaves,Min_Child_Samples,Subsample,Colsample_Bytree,Reg_Alpha,Reg_Lambda,Status
0,0,0.797172,0.706363,861,0.012387,13,98,53,0.677323,0.771258,7.366717,0.016297,COMPLETE
1,1,0.792795,0.706652,852,0.086856,14,107,86,0.775362,0.759061,5.660905,1.392307,COMPLETE
2,2,0.778497,0.745137,1070,0.279300,15,54,30,0.879372,0.799219,6.979376,4.640395,COMPLETE
3,3,0.798673,0.708193,939,0.014437,10,77,94,0.626649,0.726196,8.977661,4.456845,COMPLETE
4,4,0.796706,0.713469,1040,0.029428,5,109,54,0.881364,0.819095,2.127821,7.439481,COMPLETE

In [22]:
import joblib

joblib.dump(
    best_lgbm_pipeline,
    "best_lgbm_pipeline.pkl"
)

['best_lgbm_pipeline.pkl']

In [23]:
metrics_df = pd.DataFrame({

    "Metric": ["R2", "MAE", "RMSE"],

    "Train": [
        train_r2,
        train_mae,
        train_rmse
    ],

    "Test": [
        test_r2,
        test_mae,
        test_rmse
    ]

})

metrics_df.to_csv(
    "lgbm_final_metrics.csv",
    index=False
)

In [24]:
import pandas as pd

lgbm = pd.read_csv("lgbm_optuna_trials.csv")

lgbm

,Trial_Number,Mean_CV_R2,Mean_CV_MAE,N_Estimators,Learning_Rate,Max_Depth,Num_Leaves,Min_Child_Samples,Subsample,Colsample_Bytree,Reg_Alpha,Reg_Lambda,Status
0,0,0.797172,0.706363,861,0.012387,13,98,53,0.677323,0.771258,7.366717,0.016297,COMPLETE
1,1,0.792795,0.706652,852,0.086856,14,107,86,0.775362,0.759061,5.660905,1.392307,COMPLETE
2,2,0.778497,0.745137,1070,0.279300,15,54,30,0.879372,0.799219,6.979376,4.640395,COMPLETE
3,3,0.798673,0.708193,939,0.014437,10,77,94,0.626649,0.726196,8.977661,4.456845,COMPLETE
4,4,0.796706,0.713469,1040,0.029428,5,109,54,0.881364,0.819095,2.127821,7.439481,COMPLETE
5,5,0.792726,0.702978,1314,0.048970,15,264,68,0.742279,0.673817,2.882179,6.594755,COMPLETE
6,6,0.791402,0.713758,1041,0.100438,5,137,85,0.940015,0.865633,4.202494,0.329385,COMPLETE
7,7,0.784284,0.749640,679,0.020689,4,204,81,0.689241,0.850399,4.499549,6.149329,COMPLETE
8,8,0.797316,0.703107,831,0.048384,14,105,77,0.862528,0.734627,9.992990,7.127219,COMPLETE
9,9,0.784830,0.750875,761,0.010908,5,43,54,0.707265,0.811395,4.752622,8.311594,COMPLETE
10,10,0.789538,0.733944,345,0.021988,10,201,100,0.607286,0.998695,0.256120,3.349780,COMPLETE
11,11,0.798655,0.708553,455,0.048982,10,24,7,0.837967,0.612340,9.572441,9.483439,COMPLETE
12,12,0.789755,0.716743,401,0.159593,9,29,6,0.818849,0.608235,9.563798,9.473591,COMPLETE
13,13,0.797733,0.696672,560,0.036156,10,64,20,0.608470,0.604505,8.197725,3.956635,COMPLETE
14,14,0.799694,0.704140,1493,0.016787,8,21,35,0.986608,0.683990,8.534209,2.481352,COMPLETE
15,15,0.798746,0.696265,1470,0.016403,8,75,34,0.968505,0.701050,8.072819,2.614970,COMPLETE
16,16,0.799584,0.693860,1481,0.019825,7,153,35,0.981690,0.678454,6.405013,2.542547,COMPLETE
17,17,0.797377,0.696223,1499,0.027306,7,299,39,0.993154,0.664379,6.181058,2.159666,COMPLETE
18,18,0.795728,0.702837,1266,0.019044,7,164,21,0.923701,0.925180,6.253471,5.493473,COMPLETE
19,19,0.799477,0.699213,1289,0.010045,12,209,46,0.917860,0.667157,8.323273,1.601386,COMPLETE
20,20,0.780219,0.762381,214,0.087606,3,160,22,0.989700,0.647652,7.194569,3.170353,COMPLETE
21,21,0.798954,0.699578,1275,0.010251,12,225,44,0.928707,0.700917,8.382250,1.412419,COMPLETE
22,22,0.800016,0.700483,1379,0.013572,8,240,65,0.951181,0.643951,7.518494,1.322878,COMPLETE
23,23,0.800034,0.700040,1402,0.015213,7,238,61,0.957849,0.642290,5.540119,1.051479,COMPLETE
24,24,0.799485,0.701717,1384,0.014109,8,247,65,0.962352,0.646938,3.571384,0.743071,COMPLETE
25,25,0.799904,0.700330,1146,0.028344,6,286,66,0.889867,0.640133,5.484287,1.062436,COMPLETE
26,26,0.799736,0.700445,1175,0.027107,6,298,66,0.903686,0.637398,5.320245,0.757340,COMPLETE
27,27,0.798349,0.701772,1136,0.038247,6,263,70,0.948644,0.724980,5.409753,1.657378,COMPLETE
28,28,0.798031,0.700780,1372,0.034118,6,266,61,0.845726,0.633494,3.512606,3.539588,COMPLETE
29,29,0.793837,0.721800,1220,0.064972,3,237,58,0.894280,0.757488,7.470997,0.011510,COMPLETE

In [25]:
lgbm.loc[
    lgbm["Mean_CV_R2"].idxmax()
]

Trial_Number               23
Mean_CV_R2           0.800034
Mean_CV_MAE           0.70004
N_Estimators             1402
Learning_Rate        0.015213
Max_Depth                   7
Num_Leaves                238
Min_Child_Samples          61
Subsample            0.957849
Colsample_Bytree      0.64229
Reg_Alpha            5.540119
Reg_Lambda           1.051479
Status               COMPLETE
Name: 23, dtype: object