In [1]:


import joblib

X_train = joblib.load(
    "X_train_strat.pkl"
)

X_test = joblib.load(
    "X_test_strat.pkl"
)

y_train = joblib.load(
    "y_train_strat.pkl"
)

y_test = joblib.load(
    "y_test_strat.pkl"
)

In [2]:


import numpy as np
import optuna

from sklearn.pipeline import Pipeline

from sklearn.impute import SimpleImputer

from sklearn.preprocessing import StandardScaler

from sklearn.feature_selection import (
    VarianceThreshold,
    SelectKBest,
    f_regression
)

from sklearn.svm import SVR

from sklearn.model_selection import cross_validate

from sklearn.metrics import (
    r2_score,
    mean_absolute_error,
    mean_squared_error
)

In [3]:


preprocessor = Pipeline([

    (
        "imputer",
        SimpleImputer(strategy="median")
    ),

    (
        "variance_filter",
        VarianceThreshold(threshold=0.01)
    ),

    (
        "scaler",
        StandardScaler()
    ),

    (
        "feature_selection",
        SelectKBest(
            score_func=f_regression,
            k=1000
        )
    )

])

In [6]:
from sklearn.model_selection import cross_validate
import numpy as np

def objective(trial):

    model = SVR(

        C=trial.suggest_float(
            "C",
            1e-2,
            1e3,
            log=True
        ),

        epsilon=trial.suggest_float(
            "epsilon",
            1e-4,
            1.0,
            log=True
        ),

        gamma=trial.suggest_categorical(
            "gamma",
            ["scale", "auto"]
        ),

        kernel="rbf"
    )

    pipeline = Pipeline([

        (
            "preprocessing",
            preprocessor
        ),

        (
            "model",
            model
        )

    ])

    scores = cross_validate(

        pipeline,

        X_train,

        y_train,

        cv=5,

        scoring={

            "r2": "r2",

            "mae": "neg_mean_absolute_error"

        },

        n_jobs=-1

    )

    mean_r2 = np.mean(
        scores["test_r2"]
    )

    mean_mae = -np.mean(
        scores["test_mae"]
    )

    trial.set_user_attr(
        "mean_r2",
        mean_r2
    )

    trial.set_user_attr(
        "mean_mae",
        mean_mae
    )

    print(
        f"Trial {trial.number} | "
        f"Mean R2 = {mean_r2:.4f} | "
        f"Mean MAE = {mean_mae:.4f}"
    )

    return mean_r2

In [7]:
study = optuna.create_study(
    direction="maximize"
)

study.optimize(
    objective,
    n_trials=30,
    show_progress_bar=True
)

[I 2026-06-08 16:38:30,599] A new study created in memory with name: no-name-60600a89-bcfe-4095-ba57-52a87e318315

  0%|          | 0/30 [00:00<?, ?it/s]

Trial 0 | Mean R2 = 0.7076 | Mean MAE = 0.8886
[I 2026-06-08 16:39:51,720] Trial 0 finished with value: 0.7076346949089506 and parameters: {'C': 0.25137391690465716, 'epsilon': 0.043301188946018504, 'gamma': 'scale'}. Best is trial 0 with value: 0.7076346949089506.
Trial 1 | Mean R2 = 0.7193 | Mean MAE = 0.8113
[I 2026-06-08 16:41:19,002] Trial 1 finished with value: 0.719336818225616 and parameters: {'C': 523.2806087916287, 'epsilon': 0.0067717544196994614, 'gamma': 'scale'}. Best is trial 1 with value: 0.719336818225616.
Trial 2 | Mean R2 = 0.7688 | Mean MAE = 0.7421
[I 2026-06-08 16:42:33,441] Trial 2 finished with value: 0.7688427938738284 and parameters: {'C': 1.7064424581777824, 'epsilon': 0.014793259005548719, 'gamma': 'auto'}. Best is trial 2 with value: 0.7688427938738284.
Trial 3 | Mean R2 = 0.7738 | Mean MAE = 0.7244
[I 2026-06-08 16:44:55,163] Trial 3 finished with value: 0.7738474817112408 and parameters: {'C': 2.792937027763292, 'epsilon': 0.010969074683409297, 'gamma': 'auto'}. Best is trial 3 with value: 0.7738474817112408.
Trial 4 | Mean R2 = 0.7736 | Mean MAE = 0.7193
[I 2026-06-08 16:46:21,537] Trial 4 finished with value: 0.7735764813805918 and parameters: {'C': 8.420394488150547, 'epsilon': 0.12837709231681418, 'gamma': 'scale'}. Best is trial 3 with value: 0.7738474817112408.
Trial 5 | Mean R2 = 0.7506 | Mean MAE = 0.7621
[I 2026-06-08 16:48:16,606] Trial 5 finished with value: 0.7505971742464521 and parameters: {'C': 50.50321387681655, 'epsilon': 0.004435441553876567, 'gamma': 'scale'}. Best is trial 3 with value: 0.7738474817112408.
Trial 6 | Mean R2 = 0.7682 | Mean MAE = 0.7622
[I 2026-06-08 16:49:06,264] Trial 6 finished with value: 0.7681804913341292 and parameters: {'C': 2.8408047174683455, 'epsilon': 0.5583057111340934, 'gamma': 'scale'}. Best is trial 3 with value: 0.7738474817112408.
Trial 7 | Mean R2 = 0.7397 | Mean MAE = 0.8202
[I 2026-06-08 16:50:27,033] Trial 7 finished with value: 0.7396603221068669 and parameters: {'C': 0.5297131126818592, 'epsilon': 0.20780053929022813, 'gamma': 'auto'}. Best is trial 3 with value: 0.7738474817112408.
Trial 8 | Mean R2 = 0.4177 | Mean MAE = 1.3720
[I 2026-06-08 16:51:52,392] Trial 8 finished with value: 0.4176663217199145 and parameters: {'C': 0.011944396203585101, 'epsilon': 0.1029006712995708, 'gamma': 'scale'}. Best is trial 3 with value: 0.7738474817112408.
Trial 9 | Mean R2 = 0.7371 | Mean MAE = 0.8062
[I 2026-06-08 16:52:57,597] Trial 9 finished with value: 0.7371045624865439 and parameters: {'C': 234.39355571366295, 'epsilon': 0.5047535935792031, 'gamma': 'scale'}. Best is trial 3 with value: 0.7738474817112408.
Trial 10 | Mean R2 = 0.5696 | Mean MAE = 1.1494
[I 2026-06-08 16:54:34,783] Trial 10 finished with value: 0.5696285245743389 and parameters: {'C': 0.03785757873625376, 'epsilon': 0.00031895044116337376, 'gamma': 'auto'}. Best is trial 3 with value: 0.7738474817112408.
Trial 11 | Mean R2 = 0.7586 | Mean MAE = 0.7430
[I 2026-06-08 16:56:27,849] Trial 11 finished with value: 0.7586119168114007 and parameters: {'C': 25.41178079944243, 'epsilon': 0.000411349879859546, 'gamma': 'auto'}. Best is trial 3 with value: 0.7738474817112408.
Trial 12 | Mean R2 = 0.7686 | Mean MAE = 0.7242
[I 2026-06-08 16:58:14,562] Trial 12 finished with value: 0.768639194073493 and parameters: {'C': 12.612390206282177, 'epsilon': 0.0012962401865074938, 'gamma': 'auto'}. Best is trial 3 with value: 0.7738474817112408.
Trial 13 | Mean R2 = 0.7729 | Mean MAE = 0.7181
[I 2026-06-08 16:59:52,156] Trial 13 finished with value: 0.7729490559313562 and parameters: {'C': 8.745747812237873, 'epsilon': 0.037651387156536896, 'gamma': 'auto'}. Best is trial 3 with value: 0.7738474817112408.
Trial 14 | Mean R2 = 0.7377 | Mean MAE = 0.7818
[I 2026-06-08 17:02:39,024] Trial 14 finished with value: 0.7377047141504707 and parameters: {'C': 104.19925473100056, 'epsilon': 0.0018164371851732977, 'gamma': 'scale'}. Best is trial 3 with value: 0.7738474817112408.
Trial 15 | Mean R2 = 0.7271 | Mean MAE = 0.8455
[I 2026-06-08 17:04:07,224] Trial 15 finished with value: 0.727108133722685 and parameters: {'C': 0.3705608310535391, 'epsilon': 0.01937746593627981, 'gamma': 'auto'}. Best is trial 3 with value: 0.7738474817112408.
Trial 16 | Mean R2 = 0.7666 | Mean MAE = 0.7505
[I 2026-06-08 17:05:30,607] Trial 16 finished with value: 0.766605074196597 and parameters: {'C': 1.4614108938202928, 'epsilon': 0.11429098599128615, 'gamma': 'auto'}. Best is trial 3 with value: 0.7738474817112408.
Trial 17 | Mean R2 = 0.7724 | Mean MAE = 0.7189
[I 2026-06-08 17:07:12,593] Trial 17 finished with value: 0.7723590013113489 and parameters: {'C': 8.794325150998057, 'epsilon': 0.0018584117454585336, 'gamma': 'scale'}. Best is trial 3 with value: 0.7738474817112408.
Trial 18 | Mean R2 = 0.6184 | Mean MAE = 1.0800
[I 2026-06-08 17:08:04,753] Trial 18 finished with value: 0.6184197106259427 and parameters: {'C': 0.08844876912995303, 'epsilon': 0.9510335519840394, 'gamma': 'auto'}. Best is trial 3 with value: 0.7738474817112408.
Trial 19 | Mean R2 = 0.7759 | Mean MAE = 0.7157
[I 2026-06-08 17:09:42,768] Trial 19 finished with value: 0.7759092079546587 and parameters: {'C': 4.66432475934106, 'epsilon': 0.04541330074752648, 'gamma': 'scale'}. Best is trial 19 with value: 0.7759092079546587.
Trial 20 | Mean R2 = 0.7692 | Mean MAE = 0.7413
[I 2026-06-08 17:11:19,860] Trial 20 finished with value: 0.7692162443744733 and parameters: {'C': 1.7295769508884213, 'epsilon': 0.03214942124730239, 'gamma': 'scale'}. Best is trial 19 with value: 0.7759092079546587.
Trial 21 | Mean R2 = 0.7754 | Mean MAE = 0.7165
[I 2026-06-08 17:12:48,746] Trial 21 finished with value: 0.775369307540833 and parameters: {'C': 6.6231418168667755, 'epsilon': 0.09118503374161072, 'gamma': 'scale'}. Best is trial 19 with value: 0.7759092079546587.
Trial 22 | Mean R2 = 0.7530 | Mean MAE = 0.7852
[I 2026-06-08 17:14:18,921] Trial 22 finished with value: 0.7529914050361542 and parameters: {'C': 0.7661679076072835, 'epsilon': 0.0001141886259833102, 'gamma': 'scale'}. Best is trial 19 with value: 0.7759092079546587.
Trial 23 | Mean R2 = 0.7759 | Mean MAE = 0.7165
[I 2026-06-08 17:15:27,385] Trial 23 finished with value: 0.7759133287355825 and parameters: {'C': 4.200888546955157, 'epsilon': 0.06164595418860771, 'gamma': 'scale'}. Best is trial 23 with value: 0.7759133287355825.
Trial 24 | Mean R2 = 0.7549 | Mean MAE = 0.7536
[I 2026-06-08 17:17:02,532] Trial 24 finished with value: 0.7548617365599279 and parameters: {'C': 41.1157774503067, 'epsilon': 0.06575419993536372, 'gamma': 'scale'}. Best is trial 23 with value: 0.7759133287355825.
Trial 25 | Mean R2 = 0.7751 | Mean MAE = 0.7258
[I 2026-06-08 17:18:16,507] Trial 25 finished with value: 0.7751323256944602 and parameters: {'C': 4.9756119781567065, 'epsilon': 0.2706346946943934, 'gamma': 'scale'}. Best is trial 23 with value: 0.7759133287355825.
Trial 26 | Mean R2 = 0.7584 | Mean MAE = 0.7447
[I 2026-06-08 17:19:31,196] Trial 26 finished with value: 0.758426172676943 and parameters: {'C': 28.269212460703407, 'epsilon': 0.06446731166814347, 'gamma': 'scale'}. Best is trial 23 with value: 0.7759133287355825.
Trial 27 | Mean R2 = 0.6822 | Mean MAE = 0.9418
[I 2026-06-08 17:20:30,708] Trial 27 finished with value: 0.6821644071683274 and parameters: {'C': 0.16505706104579523, 'epsilon': 0.2247323322357031, 'gamma': 'scale'}. Best is trial 23 with value: 0.7759133287355825.
Trial 28 | Mean R2 = 0.7358 | Mean MAE = 0.7844
[I 2026-06-08 17:22:12,705] Trial 28 finished with value: 0.7357806330879462 and parameters: {'C': 132.00491642260343, 'epsilon': 0.02205658376981265, 'gamma': 'scale'}. Best is trial 23 with value: 0.7759133287355825.
Trial 29 | Mean R2 = 0.7558 | Mean MAE = 0.7789
[I 2026-06-08 17:23:41,385] Trial 29 finished with value: 0.755754762897656 and parameters: {'C': 0.859881473365506, 'epsilon': 0.05740647888916681, 'gamma': 'scale'}. Best is trial 23 with value: 0.7759133287355825.

In [8]:
print("Best Mean CV R2:")
print(study.best_value)

print("\nBest Parameters:")
print(study.best_params)

Best Mean CV R2:
0.7759133287355825

Best Parameters:
{'C': 4.200888546955157, 'epsilon': 0.06164595418860771, 'gamma': 'scale'}

In [9]:

best_svr_pipeline = Pipeline([

    (
        "preprocessing",
        preprocessor
    ),

    (
        "model",

        SVR(

            **study.best_params,

            kernel="rbf"
        )
    )

])

best_svr_pipeline.fit(
    X_train,
    y_train
)

Pipeline(steps=[('preprocessing',
                 Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                                 ('variance_filter',
                                  VarianceThreshold(threshold=0.01)),
                                 ('scaler', StandardScaler()),
                                 ('feature_selection',
                                  SelectKBest(k=1000,
                                              score_func=<function f_regression at 0x000001CB76E20EE0>))])),
                ('model',
                 SVR(C=4.200888546955157, epsilon=0.06164595418860771))])

In [10]:
# TRAIN PREDICTIONS

y_train_pred = best_svr_pipeline.predict(
    X_train
)

# TEST PREDICTIONS

y_test_pred = best_svr_pipeline.predict(
    X_test
)

In [11]:


train_r2 = r2_score(
    y_train,
    y_train_pred
)

test_r2 = r2_score(
    y_test,
    y_test_pred
)

train_rmse = np.sqrt(
    mean_squared_error(
        y_train,
        y_train_pred
    )
)

test_rmse = np.sqrt(
    mean_squared_error(
        y_test,
        y_test_pred
    )
)

train_mae = mean_absolute_error(
    y_train,
    y_train_pred
)

test_mae = mean_absolute_error(
    y_test,
    y_test_pred
)

print("\n TUNED SVR ")

print("\nTrain R2 :", train_r2)
print("Train RMSE :", train_rmse)
print("Train MAE :", train_mae)

print("\nTest R2 :", test_r2)
print("Test RMSE :", test_rmse)
print("Test MAE :", test_mae)

 TUNED SVR

Train R2 : 0.8980741717055652
Train RMSE : 0.7552635933996131
Train MAE : 0.3519028222589842

Test R2 : 0.7931043274212117
Test RMSE : 1.0810926209606628
Test MAE : 0.6998452963652577

In [12]:
print("Best Parameters:")
print(study.best_params)

Best Parameters:
{'C': 4.200888546955157, 'epsilon': 0.06164595418860771, 'gamma': 'scale'}

In [19]:
import pandas as pd

trials_df = study.trials_dataframe()

trials_df["Mean_CV_MAE"] = [
    t.user_attrs.get("mean_mae")
    for t in study.trials
]

trials_df["Mean_CV_R2"] = [
    t.user_attrs.get("mean_r2")
    for t in study.trials
]

final_trials_df = trials_df[
    [
        "number",
        "Mean_CV_R2",
        "Mean_CV_MAE",
        "params_C",
        "params_epsilon",
        "params_gamma",
        "state"
    ]
].copy()

final_trials_df.columns = [
    "Trial_Number",
    "Mean_CV_R2",
    "Mean_CV_MAE",
    "C",
    "Epsilon",
    "Gamma",
    "Status"
]

final_trials_df.to_csv(
    "svr_optuna_trials.csv",
    index=False
)

final_trials_df.head()

,Trial_Number,Mean_CV_R2,Mean_CV_MAE,C,Epsilon,Gamma,Status
0,0,0.707635,0.888614,0.251374,0.043301,scale,COMPLETE
1,1,0.719337,0.811343,523.280609,0.006772,scale,COMPLETE
2,2,0.768843,0.742066,1.706442,0.014793,auto,COMPLETE
3,3,0.773847,0.724407,2.792937,0.010969,auto,COMPLETE
4,4,0.773576,0.719298,8.420394,0.128377,scale,COMPLETE

In [20]:
final_trials_df.head(30)

,Trial_Number,Mean_CV_R2,Mean_CV_MAE,C,Epsilon,Gamma,Status
0,0,0.707635,0.888614,0.251374,0.043301,scale,COMPLETE
1,1,0.719337,0.811343,523.280609,0.006772,scale,COMPLETE
2,2,0.768843,0.742066,1.706442,0.014793,auto,COMPLETE
3,3,0.773847,0.724407,2.792937,0.010969,auto,COMPLETE
4,4,0.773576,0.719298,8.420394,0.128377,scale,COMPLETE
5,5,0.750597,0.762125,50.503214,0.004435,scale,COMPLETE
6,6,0.768180,0.762195,2.840805,0.558306,scale,COMPLETE
7,7,0.739660,0.820161,0.529713,0.207801,auto,COMPLETE
8,8,0.417666,1.372049,0.011944,0.102901,scale,COMPLETE
9,9,0.737105,0.806174,234.393556,0.504754,scale,COMPLETE
10,10,0.569629,1.149407,0.037858,0.000319,auto,COMPLETE
11,11,0.758612,0.743039,25.411781,0.000411,auto,COMPLETE
12,12,0.768639,0.724205,12.612390,0.001296,auto,COMPLETE
13,13,0.772949,0.718133,8.745748,0.037651,auto,COMPLETE
14,14,0.737705,0.781817,104.199255,0.001816,scale,COMPLETE
15,15,0.727108,0.845501,0.370561,0.019377,auto,COMPLETE
16,16,0.766605,0.750454,1.461411,0.114291,auto,COMPLETE
17,17,0.772359,0.718937,8.794325,0.001858,scale,COMPLETE
18,18,0.618420,1.080012,0.088449,0.951034,auto,COMPLETE
19,19,0.775909,0.715659,4.664325,0.045413,scale,COMPLETE
20,20,0.769216,0.741253,1.729577,0.032149,scale,COMPLETE
21,21,0.775369,0.716459,6.623142,0.091185,scale,COMPLETE
22,22,0.752991,0.785240,0.766168,0.000114,scale,COMPLETE
23,23,0.775913,0.716478,4.200889,0.061646,scale,COMPLETE
24,24,0.754862,0.753608,41.115777,0.065754,scale,COMPLETE
25,25,0.775132,0.725826,4.975612,0.270635,scale,COMPLETE
26,26,0.758426,0.744671,28.269212,0.064467,scale,COMPLETE
27,27,0.682164,0.941801,0.165057,0.224732,scale,COMPLETE
28,28,0.735781,0.784382,132.004916,0.022057,scale,COMPLETE
29,29,0.755755,0.778913,0.859881,0.057406,scale,COMPLETE

In [17]:
trials_df.shape

(30, 13)

In [21]:
joblib.dump(
    best_svr_pipeline,
    "best_svr_pipeline.pkl"
)

['best_svr_pipeline.pkl']

In [33]:
svr = pd.read_csv("svr_optuna_trials.csv")

svr.loc[
    svr["Mean_CV_R2"].idxmax()
]

Trial_Number          23
Mean_CV_R2      0.775913
Mean_CV_MAE     0.716478
C               4.200889
Epsilon         0.061646
Gamma              scale
Status          COMPLETE
Name: 23, dtype: object